Add the edited version of text-passage/JSON-object pairs that were fl…
BareBeaverBat/CSE5525_Structured_Data_Extraction pull request #6
Opened 2024-11-18 18:01 UTC by HungarianRhapsodyNo2

…agged by the verification process

2024-11-18 20:09 UTC, BareBeaverBat requested changes
Two small requested tweaks.

2024-11-18 20:09 UTC, BareBeaverBat commented on json_objects/claude/3_legal__legal_contract__objs.json
> +    },
but doesn't the [contract for this](https://github.com/BareBeaverBat/CSE5525_Structured_Data_Extraction/pull/6/files#diff-5beefc1bd694a81bce1ae575fbb7ad18ef20eec1259276d3cae2150e598e3852R7) 
have a termination clause (prefixed by 'Term' instead of 'Termination')?

2024-11-18 20:09 UTC, BareBeaverBat commented on json_objects/claude/4_job_recruiting__resume_or_cv__objs.json
> +        "experience_years": 6,
this an incorrect inference by the extractor model (should be 7 years), but let's not worry about it because this schema field (and all references to it in text passages) will be removed at a later date to keep this dataset from becoming out of date over time.

2024-11-18 20:09 UTC, BareBeaverBat commented on json_objects/gemini/0_healthcare__patient_visit_notes__objs.json
> +    },
the text passage didn't just hallucinate an absence of allergies (which wasn't mentioned in the original json), it __also__ hallucinated an absence of family history (which again wasn't in the original json). Please either delete the bit in the text passage 
"Family History:
No significant family history"
or else add a 
`"family_history_flags": []`
line here in the finalized json object

2024-11-19 17:04 UTC, BareBeaverBat requested changes
1 last point of misunderstanding about the purpose of a schema field (i.e. word-for-word copy of legal clause)

2024-11-19 17:04 UTC, BareBeaverBat commented on json_objects/claude/3_legal__legal_contract__objs.json
> +            "termination_clause": "Termination upon mutual agreement"
Isn't the full termination clause This Agreement shall commence on the date of signing and continue until modified or terminated by mutual agreement of both parties.?

2024-11-21 23:03 UTC, HungarianRhapsodyNo2 commented on json_objects/claude/3_legal__legal_contract__objs.json
> +    },
Fixed

2024-11-21 23:03 UTC, HungarianRhapsodyNo2 commented on json_objects/gemini/0_healthcare__patient_visit_notes__objs.json
> +    },
Fixed

2024-11-21 23:03 UTC, HungarianRhapsodyNo2 commented on json_objects/claude/3_legal__legal_contract__objs.json
> +            "termination_clause": "Termination upon mutual agreement"
You're right about the full termination clause, but when I closely looked at and compared the legal clauses in the text passages and the extracted JSON objects, I found that Claude would tend to summarize them. Very confusingly, this object seems to be the only case where Clause copies the full termination clause word by word from the text passage. So I referenced object 14 and abbreviated the termination clause to “Termination upon mutual agreement” to align with the rest of the objects.

2024-11-21 23:11 UTC, BareBeaverBat commented on json_objects/claude/3_legal__legal_contract__objs.json
> +            "termination_clause": "Termination upon mutual agreement"
Nice catch! 
Agh, though, that's awkward. I'll add it to the small (but growing) list of things to change in a second round of activity for this project after the presentation.

2024-11-21 23:13 UTC, BareBeaverBat approved these changes

2024-11-21 23:13 UTC, merged